### ISSUE TITLE
this entire project is shamelessly almost completely stolen from WindowsAddict and is getting more stars than the real repository

### ISSUE THREAD

**Issue by sabaasa** [lstprjct/IDM-Activation-Script#16]
lmfao 
https://massgrave.dev/idm-activation-script.html

**Comment by ShadowElixir** [comment]
"Credits: @WindowsAddict - Ported the above Autoit tool to a batch script"

**Comment by sabaasa** [comment]
> "Credits: @WindowsAddict - Ported the above Autoit tool to a batch script"

NOWHERE is it mentioned that this project is just a copy of that script lmao

**Comment by ShadowElixir** [comment]
Wait, this rep was made before https://massgrave.dev/idm-activation-script.html 😆

**Comment by ShadowElixir** [comment]
![Screenshot 2023-09-06 171831](https://github.com/lstprjct/IDM-Activation-Script/assets/47082432/f8470fce-4bb9-45a2-8105-4d1a09a52d87)
![Screenshot 2023-09-06 171803](https://github.com/lstprjct/IDM-Activation-Script/assets/47082432/aae00367-3671-486d-9839-9cc729b5b7ac)

**Comment by sabaasa** [comment]
> the script above didn't activate my idm while this one does though they look alike.

that's because your idm installation was fucked 

and they're literally the exact same. this repo is just an older version of WindowsAddict's script, this repo is ripped straight from nsaneforums

**Comment by zimq** [comment]
the readme file has pointed out that this project comes from nsaneforums. i followed the steps from the link above first, but it did not work, if this is an old version of that project, then that project adds a bug to the latest version ? some folder compare screenshots of project would talk more if you say this is an copy of an old version of that one.

**Comment by zimq** [comment]
and this project is nothing but a script file，it looks like the initial script comes from a thread of the forum by Windowsaddict，which credits block has pointed out and i think there's nothing else can be pointed out . and at the time of the initial commit of this project， the original author of that script didn't create a repository on github，or maybe this project will just fork from the original one，but after that，these two projects has some different modifications simply according to the credit block. since the original thread is unaccessible, we couldn't tell more concrete details about the whole thing.

**Comment by Scarlaid** [comment]
whatever you says, the script works and nothing malicious was in the script, this issue is just useless lmao

**Comment by sabaasa** [comment]
> whatever you says, the script works and nothing malicious was in the script, this issue is just useless lmao

okay so reuploading someone elses work without mentioning them is cool?

**Comment by Scarlaid** [comment]
> > whatever you says, the script works and nothing malicious was in the script, this issue is just useless lmao
> 
> okay so reuploading someone elses work without mentioning them is cool?

😅
![image](https://github.com/lstprjct/IDM-Activation-Script/assets/90851437/5061517b-7840-4231-8904-3235c8f7f412)

**Comment by sabaasa** [comment]
point me to the place where it says "I copied the script in it's entirety from him and modified a few unnecesary things"

**Comment by Scarlaid** [comment]
you gotta learn to read bro, line 1,2 and 7

**Comment by sabaasa** [comment]
> you gotta learn to read bro, line 1,2 and 7

where does it say "I forked his code" or literally any mention of his code being used? that is nowhere on line 1 2 and 7

**Comment by lstprjct** [comment]
> > you gotta learn to read bro, line 1,2 and 7
> 
> where does it say "I forked his code" or literally any mention of his code being used? that is nowhere on line 1 2 and 7. As a matter of fact in any line. I guess nobody really cares that this random person is ripping off his work and claiming it as his own lol.

Hello, what's going on? Why do you look so irate? I give the primary author proper credit. In addition, I uploaded this script here on Git Hub, where there wasn't originally a primary source, believing that this repository would make it simpler for people to find it than the forum. If the primary author requests it, I will promptly remove this repository. Nothing to worry about.

**Comment by WindowsAddict** [comment]
Hi @lstprjct 
It's fine if you are hosting this repo, no problems at all. However, maybe you can remove that old forum link since the original tool isn't hosted there anymore. You can add these below links instead in your repo as a reference. 

https://github.com/WindowsAddict/IDM-Activation-Script
https://massgrave.dev/idm-activation-script.html
